/*
  * Fergoman123's Tools
  * Copyright (c) 2014 fergoman123.
  * All rights reserved. This program and the accompanying materials
  * are made available under the terms of the GNU Lesser Public License v2.1
  * which accompanies this distribution, and is available at
  * http://www.gnu.org/licenses/gpl-3.0.html
  */

package io.github.fergoman123.fergotools.reference.gui;


import net.minecraftforge.fml.common.ModMetadata;

/**
 * a manual mcmod.info file with no need to have the file
 */
public class MetadataFT
{

    public static void writeMetadata(ModMetadata metadata)
    {
        metadata.autogenerated = false;
        metadata.modId = ModInfo.modid;
        metadata.name = ModInfo.name;
        metadata.version = ModInfo.versionMain;
        metadata.description = ModInfo.description;
        metadata.authorList = ModInfo.authorList;
        metadata.logoFile = ModInfo.logoFile;
        metadata.url = ModInfo.url;
        metadata.updateUrl = ModInfo.updateUrl;
    }
}
