package io.github.fergoman123.fergotools.reference;

import net.minecraftforge.fml.common.ModMetadata;

public class MetadataFT {
    public static void writeMetadata(ModMetadata md){
        md.autogenerated = false;
        md.modId = ModInfo.modid;
        md.name = ModInfo.name;
        md.version = ModInfo.versionMain;
        md.description = ModInfo.description;
        md.authorList = ModInfo.authorList;
        md.logoFile = ModInfo.logoFile;
        md.url = ModInfo.url;
        md.updateUrl = ModInfo.updateUrl;
    }
}
