package fergoman123.mods.fergotools.lib;

import cpw.mods.fml.common.ModMetadata;
import fergoman123.mods.fergoutil.helper.MetadataHelper;

import java.util.List;

public class MetadataFT extends MetadataHelper{
    public MetadataFT(String modid, String name, String version, String logoFile, String author, List<String> authors, String url, String description) {
        super(modid, name, version, logoFile, author, authors, url, description);
        this.modid = ModInfo.modid;
        this.name = ModInfo.name;
        this.version = ModInfo.versionMain;
        this.logoFile = ModInfo.logoFile;
        this.author = ModInfo.author;
        this.authors = ModInfo.authorList;
        this.url = ModInfo.url;
        this.description = ModInfo.description;
    }

    public static void writeMetadata(ModMetadata metadata)
    {
        metadata.autogenerated = false;
        metadata.modId = modid;
        metadata.name = name;
        metadata.version = version;
        metadata.description = description;
        metadata.authorList = authors;
        metadata.logoFile = logoFile;
        metadata.url = url;
        metadata.updateUrl = ModInfo.updateUrl;
    }
}
