package fergoman123.mods.fergotools.lib;

import cpw.mods.fml.common.ModMetadata;
import fergoman123.mods.fergoutil.helper.NameHelper;

import java.util.Arrays;

public class ModInfo {
	
	public static final String modid = "FergoTools";
    public static final String name = "Fergoman123's Tools";
    public static final String versionMain = "1.7.2-2.0";
    public static final String version = "@version@";
    public static final String dep = "required-after:FergoUtil";
    public static final String url = "fergoman123.github.io";
    public static final String updateUrl = "fergoman123.github.io/fergotools.html";
    
    public static final String channel = modid;
    
    public static final String description = "Add a heap of new Tools into Minecraft";
    
    public static final String author = "fergoman123";
    public static final String logoFile = "/assets/fergotools/textures/art/logo.png";

    public static void writeMetadata(ModMetadata metadata)
    {
        metadata.autogenerated = false;
        metadata.modId = modid;
        metadata.name = name;
        metadata.version = versionMain;
        metadata.description = description;
        metadata.authorList = Arrays.asList("Fergoman123");
        metadata.logoFile = NameHelper.getLogoFile(modid.toLowerCase());
        metadata.url = url;
        metadata.updateUrl = updateUrl;
    }

}
