package io.github.fergoman123.fergotools.info;

import net.minecraftforge.fml.common.ModMetadata;

public class FTModMetadata
{
    public static void writeMetadata(ModMetadata md)
    {
        md.autogenerated = false;
        md.modId = ModInfo.modid;
        md.name = ModInfo.name;
        md.version = ModInfo.version;
        md.description =  ModInfo.description;
        md.authorList = ModInfo.authors;
        md.logoFile = ModInfo.logoFile;
        md.url = ModInfo.url;
        md.updateUrl = ModInfo.updateUrl;
    }
}
